name: insta_clone
description: A new Flutter application.
version: 1.2.3+1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  image_picker:  ^0.8.2
  firebase_storage: ^10.0.1
  firebase_auth: ^3.0.1
  uuid: ^3.0.4
  image: ^3.0.2
  font_awesome_flutter: ^9.1.0
  async: ^2.8.1
  http: ^0.13.3
  shared_preferences: ^2.0.6
  cached_network_image: ^3.1.0
  firebase_messaging: ^10.0.4
  location: ^4.3.0
  geocoder: ^0.2.1
  flare_flutter: ^3.0.1
  google_sign_in: ^5.0.3

#dev_dependencies:
#  flutter_test:
#    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
  assets:
    - assets/images/google_signin_button.png
    - assets/flare/Like.flr
